// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcQHvzNjrXcM4LVjAYuSIotW4rnnvCok',
    appId: '1:1044435889101:web:1671abd47a44bd4d58f284',
    messagingSenderId: '1044435889101',
    projectId: 'developer-portfolio-app',
    authDomain: 'developer-portfolio-app.firebaseapp.com',
    storageBucket: 'developer-portfolio-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIghPI2DTdK_9Uot6lb0_9jWU5SdoM_ug',
    appId: '1:1044435889101:android:1573f9dbe4eb167058f284',
    messagingSenderId: '1044435889101',
    projectId: 'developer-portfolio-app',
    storageBucket: 'developer-portfolio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQokSuQP-1YYxo3UhVHUHn54KMkUVjxM',
    appId: '1:1044435889101:ios:db0332f30f46276958f284',
    messagingSenderId: '1044435889101',
    projectId: 'developer-portfolio-app',
    storageBucket: 'developer-portfolio-app.firebasestorage.app',
    iosBundleId: 'com.example.portfolioManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHcQHvzNjrXcM4LVjAYuSIotW4rnnvCok',
    appId: '1:1044435889101:web:4e97234bbe2696b858f284',
    messagingSenderId: '1044435889101',
    projectId: 'developer-portfolio-app',
    authDomain: 'developer-portfolio-app.firebaseapp.com',
    storageBucket: 'developer-portfolio-app.firebasestorage.app',
  );
}
